# Element-Wise Calculations

In [1]:
import numpy as np

In [2]:
nums = np.arange(10)

In [3]:
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
new_nums = nums + 5

print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [5]:
new_nums = nums - 5

print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[-5 -4 -3 -2 -1  0  1  2  3  4]


In [6]:
new_nums = nums * 5

print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[ 0  5 10 15 20 25 30 35 40 45]


In [7]:
new_nums = nums / 5

print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


In [8]:
new_nums = nums ** 5

print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[    0     1    32   243  1024  3125  7776 16807 32768 59049]


In [9]:
new_nums = nums // 5

print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 1 1 1 1 1]


In [10]:
new_nums = nums % 5

print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 1 2 3 4]
