# NumPy Add Elements

In [1]:
import numpy as np

In [2]:
nums = np.arange(5)

nums

array([0, 1, 2, 3, 4])

## Append Item to Array

In [4]:
new_nums = np.append(nums, 5)

print(nums)
print(new_nums)

[0 1 2 3 4]
[0 1 2 3 4 5]


## Combine Lists/Arrays into a new Array

In [5]:
new_nums = np.concatenate([ nums, [5,6], [7], [8,9,10]])

print(new_nums)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
np.concatenate([ [5,6], [7], [8,9,10] ])

array([ 5,  6,  7,  8,  9, 10])

In [13]:
np.concatenate([ [[5,6,9]], [[7,1,2]], [[8,9,10]] ], axis=0)

array([[ 5,  6,  9],
       [ 7,  1,  2],
       [ 8,  9, 10]])

In [10]:
np.concatenate([ [[5,6]], [[7]], [[8,9,10]] ], axis=1)

array([[ 5,  6,  7,  8,  9, 10]])

## Insert an Item into an Array

In [15]:
new_nums = np.insert(nums, 2, 9)

print(nums)
print(new_nums)

[0 1 2 3 4]
[0 1 9 2 3 4]


In [17]:
matrix = np.concatenate([ [[5,6,9]], [[7,1,2]], [[8,9,10]] ], axis=0)

matrix

array([[ 5,  6,  9],
       [ 7,  1,  2],
       [ 8,  9, 10]])

In [18]:
np.insert(matrix, 1, 9)

array([ 5,  9,  6,  9,  7,  1,  2,  8,  9, 10])

In [19]:
np.insert(matrix, 1, [7,7,7])

array([ 5,  7,  7,  7,  6,  9,  7,  1,  2,  8,  9, 10])

In [21]:
np.insert(matrix, 1, [7,7,7], axis=0)

array([[ 5,  6,  9],
       [ 7,  7,  7],
       [ 7,  1,  2],
       [ 8,  9, 10]])

In [22]:
np.insert(matrix, 1, [7,7,7], axis=1)

array([[ 5,  7,  6,  9],
       [ 7,  7,  1,  2],
       [ 8,  7,  9, 10]])