# NumPy Array Element Selection

In [9]:
import numpy as np

In [28]:
nums = np.arange(10, 20)

nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
gt4 = nums > 14

print(type(gt4))

# nums[gt4]
nums[ [False, False, False, False, False,  True,  True,  True,  True,  True] ]

<class 'numpy.ndarray'>


array([15, 16, 17, 18, 19])

In [12]:
nums[ [1,3,5 ] ]

array([11, 13, 15])

In [15]:
nums[nums > 14] * 2

array([30, 32, 34, 36, 38])

In [30]:
# nums[nums > 14] = nums[nums > 14] * 2

gt14 = nums > 14

nums[gt14] *= 2

nums[gt14] = nums[gt14] * 2

nums

array([10, 11, 12, 13, 14, 30, 32, 34, 36, 38])

In [19]:
nums[0] = 999

nums

array([999,  11,  12,  13,  14, 120, 128, 136, 144, 152])

In [29]:
# for index, value in np.ndenumerate(nums):
#     nums[index[0]] = value * 2
    
# nums

double_me_if_gt14 = lambda value: value * 2 if value > 14 else value

double_me_if_gt14 = np.vectorize(double_me_if_gt14)

print(double_me_if_gt14(nums))

nums
    

[10 11 12 13 14 30 32 34 36 38]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
matrix_nums = np.arange(36).reshape(6,6)

matrix_nums

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [34]:
onedim_matrix_nums = matrix_nums.reshape(36)

onedim_matrix_nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [35]:
onedim_matrix_nums[5] = 9999

In [36]:
onedim_matrix_nums

array([   0,    1,    2,    3,    4, 9999,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35])

In [37]:
matrix_nums

array([[   0,    1,    2,    3,    4, 9999],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13,   14,   15,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

In [38]:
matrix_nums[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [39]:
matrix_nums[:,1]

array([ 1,  7, 13, 19, 25, 31])

In [41]:
matrix_nums[:,1:5:2]

array([[ 1,  3],
       [ 7,  9],
       [13, 15],
       [19, 21],
       [25, 27],
       [31, 33]])