# Numpy NaN and Logical Ops

In [1]:
import math
import numpy as np

In [2]:
math.nan

nan

In [3]:
np.nan

nan

In [4]:
math.nan == math.nan

False

In [5]:
np.nan == np.nan

False

In [6]:
math.isnan(math.nan)

True

In [7]:
np.isnan(np.nan)

True

In [8]:
np.isnan(math.nan)

True

In [9]:
math.isnan(np.nan)

True

In [12]:
arr = np.array([1, np.nan, 3, np.nan, 5])

arr

array([ 1., nan,  3., nan,  5.])

In [13]:
np.isnan(arr)

array([False,  True, False,  True, False])

In [14]:
arr[np.isnan(arr)]

array([nan, nan])

In [15]:
np.logical_not(np.isnan(arr))

array([ True, False,  True, False,  True])

In [16]:
arr[np.logical_not(np.isnan(arr))]

array([1., 3., 5.])

In [17]:
arr[~(np.isnan(arr))]

array([1., 3., 5.])

In [19]:
arr = np.arange(100)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
arr[np.logical_and(arr > 10, arr < 50)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

In [22]:
arr[np.logical_or(arr < 10, arr > 50)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
       75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])