# NumPy Array Ops

In [1]:
import numpy as np

In [6]:
arr1 = np.array([1,2,3], dtype=np.int16)

arr2 = np.array([4,5,6], dtype=np.int16)

arr3 = np.array([7,8], dtype=np.int16)

arr4 = np.array([7], dtype=np.int16)

In [8]:
print(arr1.shape)
print(arr2.shape)

arr1 + arr2

(3,)
(3,)


array([5, 7, 9], dtype=int16)

In [10]:
print(arr1.shape)
print(arr3.shape)

arr1 + arr3

(3,)
(2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [9]:
print(arr1.shape)
print(arr4.shape)

arr1 + arr4

(3,)
(1,)


array([ 8,  9, 10], dtype=int16)

In [11]:
arr5 = arr3[:, np.newaxis]

arr5

array([[7],
       [8]], dtype=int16)

In [12]:
print(arr1.shape)
print(arr5.shape)

(3,)
(2, 1)


In [13]:
arr1 + arr5

array([[ 8,  9, 10],
       [ 9, 10, 11]], dtype=int16)

In [14]:
np.dot( [7,], [8,] )

56

In [15]:
np.dot( [7,3], [8,2] )

62

In [22]:
vector1 = np.array( [[7, 3], [9,7]] )
vector2 = np.array( [[8],[2]] )

print(vector1.shape)
print(vector1)

print(vector2.shape)
print(vector2)


np.dot( vector1, vector2 )

(2, 2)
[[7 3]
 [9 7]]
(2, 1)
[[8]
 [2]]


array([[62],
       [86]])