# Select Transform Experiment

In [1]:
import numpy as np

initial_nums = np.arange(10_000_000)

initial_nums

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [2]:
%%time

for _ in range(1):
    nums = np.copy(initial_nums)
    
    mask = nums % 2 == 0
    #print(mask.size)
    
    vals = nums[mask] * 2
    #print(vals.size)
    
    nums[mask] = vals

print(nums[:10])

[ 0  1  4  3  8  5 12  7 16  9]
Wall time: 151 ms


In [3]:
%%time

for _ in range(1):
    nums = np.copy(initial_nums)
    
    mask = nums % 2 == 0
    #print(mask.size)
    
    nums[mask] *= 2
    
print(nums[:10])

[ 0  1  4  3  8  5 12  7 16  9]
Wall time: 143 ms


In [4]:
%%time

for _ in range(1):
    nums = np.copy(initial_nums)
    
    mask = nums % 2 == 0
    #print(mask.size)
    
    vals = nums * 2
    #print(vals.size)

    np.place(nums, nums > 0, nums * 2)
    
print(nums[:10])

[ 0  0  2  4  6  8 10 12 14 16]
Wall time: 143 ms


In [5]:
%%time

# do not set count above 1
for _ in range(1):
    nums = np.copy(initial_nums)
    for idx, val in np.ndenumerate(nums):
        if nums[idx[0]] % 2 == 0:
            nums[idx[0]] = val * 2
            
print(nums[:10])

[ 0  1  4  3  8  5 12  7 16  9]
Wall time: 8.16 s


In [6]:
%%time

# do not set count above 5
for _ in range(1):
    nums = np.copy(initial_nums)
    nums = np.vectorize(lambda x: x * 2 if x % 2 == 0 else x)(nums)
    
print(nums[:10])

[ 0  1  4  3  8  5 12  7 16  9]
Wall time: 2.01 s
