# Exercise #1

1. Create a two dimensional array populated with the numbers 0 to 63. The array should have a shape of 4 rows and 16 columns.

In [13]:
# Step 1 Solution Here

import numpy as np

arr = np.arange(64, dtype="int8").reshape(4,16)

display(arr)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]],
      dtype=int8)

2. Using the array created in the previous step, display the following:

- Element Data Type
- Number of Dimensions
- Shape
- Element Count
- Item Size in Bytes
- Array Size in Bytes

In [14]:
# Step 2 Solution Here

display(arr.dtype)
display(arr.ndim)
display(arr.shape)
display(arr.size)
display(arr.itemsize)
display(arr.nbytes)

dtype('int8')

2

(4, 16)

64

1

64

3. Subtract 10 from each element through a one-line subtraction operation.

In [15]:
# Step 3 Solution Here

arr -= 10

arr

array([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
          3,   4,   5],
       [  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
         19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,
         35,  36,  37],
       [ 38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
         51,  52,  53]], dtype=int8)

4. Multiply all even values with a -1.

In [24]:
# Step 4 Solution Here

arr[arr % 2 != 0] *= -1

arr

# if 4 % 2:
#     print("odd")
# else:
#     print("even")

# arr % 2

# arr % 2 != 0
    
# arr[arr % 2] *= -1

# arr

# arr1 = np.array([ 1,2,3 ])

# arr1[ [True, False, True ]]

# arr1[ [1, 0, 1 ]]



array([2, 1, 2])

5. Replace all negative numbers with the NaN value. You may need to change data type.

In [11]:
# Step 5 Solution

arr = arr.astype('float16')

arr[arr < 0] = np.nan

arr

array([[10., nan,  8., nan,  6., nan,  4., nan,  2., nan,  0.,  1., nan,
         3., nan,  5.],
       [nan,  7., nan,  9., nan, 11., nan, 13., nan, 15., nan, 17., nan,
        19., nan, 21.],
       [nan, 23., nan, 25., nan, 27., nan, 29., nan, 31., nan, 33., nan,
        35., nan, 37.],
       [nan, 39., nan, 41., nan, 43., nan, 45., nan, 47., nan, 49., nan,
        51., nan, 53.]], dtype=float16)

6. Transform the 2d array into a 1d array. Drop all of the NaN values.

In [12]:
# Step 6 Solution

arr[~(np.isnan(arr))]

array([10.,  8.,  6.,  4.,  2.,  0.,  1.,  3.,  5.,  7.,  9., 11., 13.,
       15., 17., 19., 21., 23., 25., 27., 29., 31., 33., 35., 37., 39.,
       41., 43., 45., 47., 49., 51., 53.], dtype=float16)